server {
  listen 80;
  server_name https://metin2migration.fly.dev;  # vagy tetszőleges

  root /usr/share/nginx/html;
  index index.html index.htm;

  location / {
    # Próbáld meg kiszolgálni, ha nem találsz statikus fájlt, akkor irányíts vissza index.html-re
    try_files $uri $uri/ /index.html;
  }

  # statikus assetek cache-elése, ha szeretnéd
  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
    expires 1y;
    add_header Cache-Control "public";
  }
}