import { defineStore } from "pinia";
import { ref } from "vue";

export const polskaStore = defineStore("items", () => {
  const polskaItems = ref([
    { name: "Lord pánt - 20%-os", price: 6 },
    { name: "1000 SÉ utalvány", price: 34.5 },
    { name: "Bátorság Köpeny (200)", price: 0.465 },
    { name: "Kvarchomok", price: 0.052 },
    { name: "Holdfény Kincsesláda (200)", price: 2.88 },
    { name: "Titán-Dioxid", price: 0.35 },
    { name: "Szürke festék", price: 0.0175 },
    { name: "Mágikus magvak", price: 0.025 },
    { name: "Víztiszta kristály", price: 0.02 },
    { name: "Démoni Hamvak", price: 0.01 },
    { name: "Kék Kristály", price: 0.01 },
    { name: "Tűzcipő +5", price: 1.8 },
    { name: "Vas ékszertároló (200)", price: 2.8 },
    { name: "Vas doboz (200)", price: 2.8 },
    { name: "Vas láda (200)", price: 3 },
    { name: "Ismeretlen gyógyszer+ (200)", price: 0.15 },
    { name: "Békanyelv", price: 0.01 },
    { name: "Ezotéria bevezető", price: 0.027 },
    { name: "Démoni Ékkő", price: 0.01 },
    { name: "Démoni Emléktárgy", price: 0.015 },
    { name: "Démoni Emléktárgy+", price: 0.035 },
    { name: "Szövetdarab+", price: 0.065 },
    { name: "Jéggömb", price: 0.015 },
    { name: "Pókláb", price: 0.1 },
    { name: "Orgona (200)", price: 0.1 },
    { name: "Harangvirág (200)", price: 0.18 },
    { name: "Alpesi Rózsa (200)", price: 0.033 },
    { name: "Zöld ital (Nagy - 200)", price: 0.052 },
    { name: "Lila ital (Nagy - 200)", price: 0.066 },
    { name: "Skorpió farok", price: 0.015 },
    { name: "Kígyófarok+", price: 0.022 },
    { name: "Vas sisak +9", price: 0.75 },
    { name: "Fehér Gyöngy", price: 0.016 },
    { name: "Kék Gyöngy", price: 0.01 },
    { name: "Vörös Gyöngy", price: 0.002 },
    { name: "Kovács Kézikönyv", price: 3.4 },
    { name: "Masszív Zsinórok (200)", price: 0.07 },
    { name: "Áldástekercs", price: 0.013 },
    { name: "Zöld sárkány-bab", price: 0.15 },
    { name: "Kék sárkány-bab", price: 0.2 },
    { name: "Rózsaszín sárkány-bab", price: 0.22 },
    { name: "Sötét Talizmán", price: 0.83 },
    { name: "Szél Talizmán", price: 3.3 },
    { name: "Jég Talizmán", price: 9.2 },
    { name: "Tűz Talizmán", price: 1.7 },
    { name: "Föld talizmán", price: 0.6 },
    { name: "Villám Talizmán", price: 4.65 },
    { name: "Mennyei könny (Kohózott)", price: 0.065 },
    { name: "Réz (Kohózott)", price: 0.04 },
    { name: "Ezüst (Kohózott)", price: 0.07 },
    { name: "Réz Nyaklánc +9 (alap)", price: 0.02 },
    { name: "Fa cipő +9 (alap)", price: 0.01 },
    { name: "Ébenfa Fülbevaló +9 (alap)", price: 0.056 },
    { name: "Lánc Csuklya (+5 - 15% villám)", price: 6 },
    { name: "Nixie Láda", price: 0.028 },
    { name: "Nixie Kulcs", price: 0.0575 },
    { name: "A kard aurája készségkönyv", price: 0.14 },
    { name: "41 ÁK varjúacél +7", price: 7 },
    { name: "Békacomb", price: 0.01 },
    { name: "jégdarab+", price: 0.025 },
    { name: "farkasszőr+ (200db)", price: 0.4 },
    { name: "ékkődarab", price: 0.01 },
    { name: "Leltárbővítő", price: 0.15 },
    { name: "Sárkány karom", price: 0.1 },
    { name: "Sárkány pikkely", price: 0.04 },
    { name: "Nessie Tojás", price: 0.03 },
    { name: "Razador Tojás", price: 0.05 },
    { name: "Vad harcos könyv", price: 0.02 },
    { name: "Középszerű káosz-kő", price: 0.1 },
    { name: "Közönséges káosz-kő", price: 0.07 },
    { name: "Tűzvörös kő", price: 0.4 },
    { name: "Halálos lemezvért +9 (alap)", price: 3 },
    { name: "Acél csuklya +9 (alap)", price: 2.5 },
    { name: "Fekete Mágia vért +9 (alap)", price: 2 },
    { name: "Feketevas vért +9 (alap)", price: 1.9 },
    { name: "Mennyei könny fülbevaló +9 (alap)", price: 1.35 },
    { name: "Mennyei könny nyaklánc +9 (alap)", price: 5 },
    { name: "Mennyei könny karkötő +9 (alap)", price: 6 },
    { name: "Ezüst nyaklánc +9 (alap)", price: 1.33 },
    { name: "kagyló (200)", price: 0.04 },
    { name: "Bambuszbőr cipő +9 (alap)", price: 1 },
    { name: "Sárkánytűz (b)", price: 1.35 },
    { name: "Legendás Sárkány Gáránát", price: 1.4 },
    { name: "Mítikus Sárkány Gáránát", price: 4.14 },
    { name: "Mítikus Sárkány Jáde", price: 6 },
    { name: "Zen-bab", price: 0.025 },
  ]);

  function getPolskaItems() {
    return polskaItems.value;
  }

  return {
    polskaItems,
    
    getPolskaItems,
  };
});
